/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.popUps;

import gui.SaleManage;
import static java.lang.String.valueOf;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import raven.popup.GlassPanePopup;

/**
 *
 * @author thida
 */
public class productSelect extends javax.swing.JPanel {

    public void setSalesmange(SaleManage salesmange) {
        this.salesmange = salesmange;
    }

    public SaleManage getSalesmange() {
        return salesmange;
    }

    private SaleManage salesmange;

    private void loadTable() {
        try {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            ResultSet rs = MySQL.execute("SELECT * FROM `product` INNER JOIN `stock` ON `product`.id = `stock`.`product_id` INNER JOIN `brand` ON `product`.`brand_id` = `brand`.`id`");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(String.valueOf(rs.getInt("product_id")));
                v.add(rs.getString("brand"));
                v.add(rs.getString("name"));
                v.add(String.valueOf(rs.getInt("stock.id")));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("qty"));

                model.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void rest() {
        loadTable();
        jTextField1.setEditable(true);
        addButton.setEnabled(false);
        jTextField1.setText("");
        jTable1.clearSelection();
    }

    /**
     * Creates new form productSelect
     */
    public productSelect() {
        initComponents();
        loadTable();
        addButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        qtyField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(644, 463));
        setMinimumSize(new java.awt.Dimension(644, 463));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Brand", "Name", "Stock ID", "Selling Price", "QTY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetButton)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jTextField1.putClientProperty("JTextField.placeholderText", "Search");
        qtyField.putClientProperty("JTextField.placeholderText", "QTY");
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        int row = jTable1.getSelectedRow();

        String strProductId = String.valueOf(jTable1.getValueAt(row, 0));
        String strStockId = String.valueOf(jTable1.getValueAt(row, 3));
        String strQty = String.valueOf(jTable1.getValueAt(row, 5));

        if (!qtyField.getText().isEmpty()) {
            int checkQty = Integer.parseInt(strQty);
            int qty = Integer.parseInt(qtyField.getText());
            if (qty <= checkQty) {

                salesmange.addTable(strProductId, strStockId, qty);
                GlassPanePopup.closePopupAll();
            } else {
                JOptionPane.showMessageDialog(this, "Not enough stocks!", "Warning", JOptionPane.WARNING_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Add qty", "Warning", JOptionPane.WARNING_MESSAGE);

        }

        // setSalesmange(new SaleManage());
        //  pass.addTable(productId, stockId);

    }//GEN-LAST:event_addButtonActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String query = "SELECT * FROM `product` INNER JOIN `stock` ON `product`.id = `stock`.`product_id` INNER JOIN `brand` ON `product`.`brand_id` = `brand`.`id` ";

        if (!jTextField1.getText().isEmpty()) {
            String searchText = jTextField1.getText();
            if (query.contains("WHERE")) {
                query += " OR `name` LIKE('" + searchText + "%') OR `product_id` LIKE('" + searchText + "%') OR `brand` LIKE('" + searchText + "%')";
            } else {
                query += " WHERE `name` LIKE('" + searchText + "%') OR `product_id` LIKE('" + searchText + "%') OR `brand` LIKE('" + searchText + "%')";
            }
        }

        System.out.println(query);

        try {

            ResultSet rs = MySQL.execute(query);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(String.valueOf(rs.getInt("product_id")));
                v.add(rs.getString("brand"));
                v.add(rs.getString("name"));
                v.add(String.valueOf(rs.getInt("stock.id")));
                v.add(rs.getString("selling_price"));
                v.add(rs.getString("qty"));

                model.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        rest();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTextField1.setEditable(false);
        addButton.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField qtyField;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
